
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: npm run dev
    restart: always
  